version: "3.8"

services:
  go-ingest:
    build: ./go-ingest
    ports:
      - "8080:8080"
   

  ml-service:
    build: ./ml-service
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]
