version: '3.8'

services:
  ml-service:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - PYTHONPATH=/app
      - DATA_ROOT=/app/data
      - LOG_LEVEL=INFO
    volumes:
      - ml-data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '2.0'
    networks:
      - fetal-monitor-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - ml-service
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
    networks:
      - fetal-monitor-network

networks:
  fetal-monitor-network:
    driver: bridge

volumes:
  ml-data:
    driver: local